### ISSUE TITLE
Iterationsplan04 bearbeiten

### ISSUE THREAD

**Issue by Norinofa** [Norinofa/I8-SE#17]

**Comment by AnswerThirtyTwo** [comment]
Bearbeitest du die Zeitintervalle zu den Iterationen, da diese mir eher sehr unregelmäßig erscheinen.
Dokumentation und Protokolle müssten vllt. noch aufgeschrieben werden.

**Comment by Norinofa** [comment]
Ja habe ich auch grade bemerkt. Danke. Ich bearbeite die morgen mal.
